// Stage 3a.1 — Batch Quantifier output schema.
//
// Stage 3a.1 takes a batch of 15–25 SelectedRecommendation entries and emits
// SequencedRecommendation[] with quantified_impact + action_items per rec.
// The container types it consumes/emits live in pipelineTypes.ts; this file
// owns only the per-batch wrapper types and the zod shape that validates the
// LLM's response before it leaves the stage.
//
// Cross-batch validation (orphan refs, coverage gaps, flag union) is Stage
// 3a.2's job; this schema validates ONLY per-batch invariants.

import { z } from "zod";
import type {
  ActionItem,
  SequencedRecommendation,
  SequencerFlags3a,
} from "./pipelineTypes";

// ────────────────────────────────────────────────────────────────────────
// Batch context — what Stage 3a.1 needs to know about sibling batches so it
// can emit cross-batch sequencing references without inventing rec_ids.
// ────────────────────────────────────────────────────────────────────────

export interface BatchContext {
  batch_index: number;
  total_batches: number;
  preceding_batch_rec_ids: string[];
  following_batch_rec_ids: string[];
}

export const BatchContextSchema = z.object({
  batch_index: z.number().int().nonnegative(),
  total_batches: z.number().int().positive(),
  preceding_batch_rec_ids: z.array(z.string()),
  following_batch_rec_ids: z.array(z.string()),
});

// ────────────────────────────────────────────────────────────────────────
// Zod shapes for SequencedRecommendation, ActionItem, and the flag bag.
// These mirror the TypeScript types in pipelineTypes.ts. Keep in sync.
// ────────────────────────────────────────────────────────────────────────

const NumericValueSchema = z.object({
  value: z.union([z.number(), z.tuple([z.number(), z.number()])]),
  unit: z.enum(["USD", "percent", "count", "years"]),
  narrative_context: z.string().optional(),
  is_approximate: z.boolean().optional(),
  known_unknown: z.boolean().optional(),
  is_annual: z.boolean().optional(),
});

const RecommendationCategoryEnum = z.enum([
  "Tax",
  "Estate",
  "Entity Structure",
  "Risk & Insurance",
  "Retirement",
  "Investment",
  "Succession & Continuity",
  "Family",
  "Charitable",
  "Specialty",
]);

const ActionOwnerEnum = z.enum([
  "PSA",
  "CPA",
  "Attorney",
  "Client",
  "Banker",
  "Insurance Broker",
  "Other",
]);

const TimingBucketEnum = z.enum([
  "0-30 days",
  "30-60 days",
  "60-120 days",
  "4-6 months",
  "6-12 months",
  "12-24 months",
  "Ongoing",
]);

const CheckInCadenceEnum = z.enum([
  "weekly",
  "biweekly",
  "monthly",
  "quarterly",
  "annually",
]);

const PartnerTypeEnum = z.enum([
  "CPA",
  "Estate Attorney",
  "Business Attorney",
  "M&A Counsel",
  "Commercial P&C",
  "Health Insurance Broker",
  "Banker",
  "Valuation Provider",
  "Specialty Tax Credits",
  "Other",
]);

const DurationClassEnum = z.enum(["point_in_time", "short_running", "long_running"]);

const PlanSectionEnum = z.enum([
  "Executive Summary",
  "Your Situation",
  "Goals and Priorities",
  "Recommendations — Personal Tax",
  "Recommendations — Business Tax",
  "Recommendations — Entity Structure",
  "Recommendations — Estate Planning",
  "Recommendations — Risk & Insurance",
  "Recommendations — Retirement & Benefits",
  "Recommendations — Investment & Cash",
  "Recommendations — Succession & Continuity",
  "Recommendations — Family",
  "Recommendations — Charitable Planning",
  "Recommendations — Specialty",
  "Pre-Transaction Sequence",
  "Implementation Timeline",
  "Strategies Considered But Not Included",
  "Open Items and Decisions Needed",
  "References",
  "Disclosures",
]);

const AutoGeneratedReminderTemplateSchema = z.object({
  trigger_threshold_days: z.number().int().positive(),
  cadence: CheckInCadenceEnum,
  reminder_text_template: z.string().min(1),
});

const ActionItemSchema = z
  .object({
    action_item_id: z.string().min(1),
    description: z.string().min(1),
    sub_steps: z.array(z.string()),
    category: RecommendationCategoryEnum,
    source_recommendation_id: z.string().regex(/^REC-[A-Z]{3}-\d{3}$/),
    source_phase_or_step: z.string(),
    owner: ActionOwnerEnum,
    owner_name: z.string().nullable(),
    timing_bucket: TimingBucketEnum,
    depends_on: z.array(z.string()),
    is_decision_needed: z.boolean(),

    // Lifecycle additions populated by Stage 3a.1.
    duration_class: DurationClassEnum,
    check_in_cadence: CheckInCadenceEnum.nullable(),
    partner_required: z.boolean(),
    partner_type: PartnerTypeEnum.nullable(),
    parent_action_item_id: z.string().nullable(),
    is_derivative_reminder: z.boolean(),
    source_plan_id: z.string().nullable(),
    auto_generated_reminder_template: AutoGeneratedReminderTemplateSchema.nullable(),
  })
  .superRefine((ai, ctx) => {
    // long_running ⇔ check_in_cadence !== null ⇔ auto_generated_reminder_template !== null
    const longRunning = ai.duration_class === "long_running";
    const cadencePresent = ai.check_in_cadence !== null;
    const templatePresent = ai.auto_generated_reminder_template !== null;
    if (longRunning !== cadencePresent || longRunning !== templatePresent) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: duration_class === 'long_running' ⇔ check_in_cadence !== null ⇔ auto_generated_reminder_template !== null. All three must agree.",
      });
    }

    // partner_required ⇔ partner_type !== null
    if (ai.partner_required && ai.partner_type === null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: partner_required === true requires partner_type !== null.",
      });
    }
    if (!ai.partner_required && ai.partner_type !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: partner_required === false requires partner_type === null.",
      });
    }

    // Stage 3a.1 never sets these.
    if (ai.is_derivative_reminder) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: is_derivative_reminder must be false at Stage 3a.1 emit time.",
      });
    }
    if (ai.parent_action_item_id !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: parent_action_item_id must be null at Stage 3a.1 emit time.",
      });
    }
    if (ai.source_plan_id !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: source_plan_id must be null at Stage 3a.1 emit time.",
      });
    }

    // Cadence-to-trigger_threshold_days deterministic mapping.
    if (ai.auto_generated_reminder_template !== null && ai.check_in_cadence !== null) {
      const expected: Record<string, number> = {
        weekly: 7,
        biweekly: 14,
        monthly: 30,
        quarterly: 90,
        annually: 365,
      };
      const want = expected[ai.check_in_cadence];
      if (
        want !== undefined &&
        ai.auto_generated_reminder_template.trigger_threshold_days !== want
      ) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `ActionItem invariant: auto_generated_reminder_template.trigger_threshold_days must be ${want} for cadence '${ai.check_in_cadence}', got ${ai.auto_generated_reminder_template.trigger_threshold_days}.`,
        });
      }
      if (ai.auto_generated_reminder_template.cadence !== ai.check_in_cadence) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `ActionItem invariant: auto_generated_reminder_template.cadence must equal check_in_cadence ('${ai.check_in_cadence}'), got '${ai.auto_generated_reminder_template.cadence}'.`,
        });
      }
    }
  });

const QuantifiedImpactSchema = z
  .object({
    estimate: NumericValueSchema.nullable(),
    formula_id: z.string().nullable(),
    formula_source_file: z.string().nullable(),
    computation_inputs: z.record(z.string(), z.unknown()),
    pending_reconciliation: z.boolean(),
    alternative_values: z.array(
      z.object({
        value: NumericValueSchema,
        formula_variant: z.string(),
        awaiting: z.string(),
        context: z.string(),
      }),
    ),
    qualitative_phrasing: z.string().nullable(),
    reason_no_formula: z.string().nullable(),
    blocked_inputs: z.array(
      z.object({
        input_name: z.string(),
        blocked_reason: z.string(),
        source: z.string(),
        would_unblock_when: z.string(),
      }),
    ),
  })
  .superRefine((qi, ctx) => {
    // State A: estimate !== null ⇒ no blocked_inputs, no alternative_values, no qualitative_phrasing
    if (qi.estimate !== null) {
      if (qi.blocked_inputs.length > 0) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message:
            "QuantifiedImpact State A invariant: estimate !== null requires blocked_inputs to be empty.",
        });
      }
      if (qi.alternative_values.length > 0) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message:
            "QuantifiedImpact State A invariant: estimate !== null requires alternative_values to be empty.",
        });
      }
      if (qi.qualitative_phrasing !== null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message:
            "QuantifiedImpact State A invariant: estimate !== null requires qualitative_phrasing to be null.",
        });
      }
    }

    // State C: alternative_values.length > 0 ⇔ pending_reconciliation === true
    if (qi.alternative_values.length > 0 && !qi.pending_reconciliation) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "QuantifiedImpact State C invariant: alternative_values.length > 0 requires pending_reconciliation === true.",
      });
    }
    if (qi.pending_reconciliation && qi.alternative_values.length === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "QuantifiedImpact State C invariant: pending_reconciliation === true requires alternative_values to be non-empty.",
      });
    }

    // State B: blocked_inputs.length > 0 ⇒ estimate === null
    if (qi.blocked_inputs.length > 0 && qi.estimate !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "QuantifiedImpact State B invariant: blocked_inputs.length > 0 requires estimate === null.",
      });
    }

    // State D: reason_no_formula !== null ⇒ estimate === null AND formula_id === null AND qualitative_phrasing !== null
    if (qi.reason_no_formula !== null) {
      if (qi.estimate !== null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message:
            "QuantifiedImpact State D invariant: reason_no_formula !== null requires estimate === null.",
        });
      }
      if (qi.formula_id !== null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message:
            "QuantifiedImpact State D invariant: reason_no_formula !== null requires formula_id === null.",
        });
      }
      if (qi.qualitative_phrasing === null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message:
            "QuantifiedImpact State D invariant: reason_no_formula !== null requires qualitative_phrasing !== null.",
        });
      }
    }
  });

const ScenarioRangeSchema = z.object({
  low_value: z.number(),
  midpoint_value: z.number(),
  high_value: z.number(),
  computation_method: z.string(),
});

const SequencedRecommendationSchema = z.object({
  recommendation_id: z.string().regex(/^REC-[A-Z]{3}-\d{3}$/),
  source_file_path: z.string(),
  category: RecommendationCategoryEnum,
  status: z.enum(["Active", "Active-Cautioned", "Advanced", "Landmine", "Deprecated"]),
  position_in_sequence: z.number().int(),
  plan_section: PlanSectionEnum.nullable(),
  subsection_within_section: z.string().nullable(),
  co_triggered_with: z.array(z.string()),
  quantified_impact: QuantifiedImpactSchema,
  scenario_range: ScenarioRangeSchema.nullable(),
  timing_bucket: TimingBucketEnum,
  owner: ActionOwnerEnum,
  owner_name: z.string().nullable(),
  decisions_needed: z.boolean(),
  cluster_id: z.string().nullable(),
  cluster_sequence_closer: z.string().nullable(),
  action_items: z.array(ActionItemSchema),
  landmine: z.boolean(),
  landmine_status: z.string(),
  default_excluded: z.boolean(),
  plan_output_variant: z.enum(["default_excluded", "authorized"]).nullable(),
  match_strength: z.enum(["strong", "borderline"]),
  _audit_notes: z.string().nullable(),
});

const SequencerFlags3aSchema = z.object({
  unenumerated_question_ids: z.array(
    z.object({
      rec_id: z.string(),
      marker_text: z.string(),
      source_file: z.string(),
      context: z.string(),
    }),
  ),
  formula_yielded_unviable_value: z.array(
    z.object({
      rec_id: z.string(),
      formula_id: z.string(),
      computed_value: z.number(),
      reason: z.string(),
    }),
  ),
  cluster_closer_skipped: z.array(
    z.object({
      cluster_id: z.string(),
      member_rec_ids: z.array(z.string()),
      rationale: z.string(),
    }),
  ),
  section_assignment_ambiguity: z.array(
    z.object({
      rec_id: z.string(),
      source_metadata_text: z.string(),
      candidate_sections: z.array(PlanSectionEnum),
    }),
  ),
  timing_bucket_inferred: z.array(
    z.object({
      action_item_id: z.string(),
      inferred_bucket: TimingBucketEnum,
      source_signal: z.string(),
    }),
  ),
  qualitative_fallback_used: z.array(
    z.object({
      rec_id: z.string(),
      phrasing_used: z.string(),
      reason: z.string(),
    }),
  ),
  blocked_inputs_summary: z.array(
    z.object({
      rec_id: z.string(),
      blocked_inputs: z.array(z.string()),
      awaiting: z.array(z.string()),
    }),
  ),
  // Stage 3a.2 cross-batch flags. Stage 3a.1 emits these as empty arrays;
  // Stage 3a.2 populates them.
  orphan_action_item_dependencies: z.array(
    z.object({
      source_action_item_id: z.string(),
      source_rec_id: z.string(),
      missing_dependency_id: z.string(),
      source_batch_index: z.number().int().nonnegative(),
    }),
  ),
  orphan_sequencing_references: z.array(
    z.object({
      source_rec_id: z.string(),
      field: z.enum([
        "must_come_after",
        "must_come_before",
        "sequenced_with",
        "coordinated_with",
        "mutually_exclusive_with",
      ]),
      missing_rec_id: z.string(),
      source_batch_index: z.number().int().nonnegative(),
    }),
  ),
  batch_failures_summary: z.array(
    z.object({
      batch_index: z.number().int().nonnegative(),
      failure_type: z.string(),
      failure_reason: z.string(),
    }),
  ),
  coverage_gaps: z.array(z.string()),
  volatile_rates_stale: z.array(
    z.object({
      batch_index: z.number().int().nonnegative(),
      last_refreshed: z.string(),
      days_since_refresh: z.number().int().nonnegative(),
    }),
  ),
});

// ────────────────────────────────────────────────────────────────────────
// The full post-fill body — what Stage 3a.1's harness validates against
// AFTER it merges the always-null/derivable fields onto the LLM output.
// ────────────────────────────────────────────────────────────────────────

export const Stage3a1ResponseBodySchema = z.object({
  batch_index: z.number().int().nonnegative(),
  total_batches: z.number().int().positive(),
  recommendations: z.array(SequencedRecommendationSchema),
  _stage_flags: SequencerFlags3aSchema,
});

export type Stage3a1ResponseBody = z.infer<typeof Stage3a1ResponseBodySchema>;

// Re-export the inferred SequencedRecommendation shape so mock tests can
// consume it without a separate schema import path.
export type ValidatedSequencedRecommendation = z.infer<typeof SequencedRecommendationSchema>;
export type ValidatedActionItem = z.infer<typeof ActionItemSchema>;

// ────────────────────────────────────────────────────────────────────────
// Narrower LLM-output schema. Five fields are stripped from what the LLM
// must emit and post-filled by the harness:
//
//   At ActionItem level:
//     - owner_name              (always null at Stage 3a.1)
//     - parent_action_item_id   (always null at Stage 3a.1)
//     - is_derivative_reminder  (always false at Stage 3a.1)
//     - source_plan_id          (always null at Stage 3a.1)
//
//   At SequencedRecommendation level:
//     - source_file_path        (deterministic; the harness already loaded it)
//
// Empirically (Holloway Estate batch), these five fields contributed ~10%
// of per-rec output tokens. Removing them frees output budget without
// losing any information — the post-fill restores them deterministically
// before the full schema validates.
//
// The narrower schema preserves the State-shape and lifecycle invariants
// that depend on LLM-emitted fields (duration_class ⇔ check_in_cadence ⇔
// auto_generated_reminder_template; partner_required ⇔ partner_type).
// It drops the invariant checks for the four ActionItem fields it omits
// (those are guaranteed by the post-fill assignment).
// ────────────────────────────────────────────────────────────────────────

const Stage3a1LlmActionItemSchema = z
  .object({
    action_item_id: z.string().min(1),
    description: z.string().min(1),
    sub_steps: z.array(z.string()),
    category: RecommendationCategoryEnum,
    source_recommendation_id: z.string().regex(/^REC-[A-Z]{3}-\d{3}$/),
    source_phase_or_step: z.string(),
    owner: ActionOwnerEnum,
    timing_bucket: TimingBucketEnum,
    depends_on: z.array(z.string()),
    is_decision_needed: z.boolean(),

    // Lifecycle additions populated by Stage 3a.1.
    duration_class: DurationClassEnum,
    check_in_cadence: CheckInCadenceEnum.nullable(),
    partner_required: z.boolean(),
    partner_type: PartnerTypeEnum.nullable(),
    auto_generated_reminder_template: AutoGeneratedReminderTemplateSchema.nullable(),
  })
  .superRefine((ai, ctx) => {
    // long_running ⇔ check_in_cadence !== null ⇔ auto_generated_reminder_template !== null
    const longRunning = ai.duration_class === "long_running";
    const cadencePresent = ai.check_in_cadence !== null;
    const templatePresent = ai.auto_generated_reminder_template !== null;
    if (longRunning !== cadencePresent || longRunning !== templatePresent) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: duration_class === 'long_running' ⇔ check_in_cadence !== null ⇔ auto_generated_reminder_template !== null. All three must agree.",
      });
    }

    // partner_required ⇔ partner_type !== null
    if (ai.partner_required && ai.partner_type === null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: partner_required === true requires partner_type !== null.",
      });
    }
    if (!ai.partner_required && ai.partner_type !== null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "ActionItem invariant: partner_required === false requires partner_type === null.",
      });
    }

    // Cadence-to-trigger_threshold_days deterministic mapping.
    if (ai.auto_generated_reminder_template !== null && ai.check_in_cadence !== null) {
      const expected: Record<string, number> = {
        weekly: 7,
        biweekly: 14,
        monthly: 30,
        quarterly: 90,
        annually: 365,
      };
      const want = expected[ai.check_in_cadence];
      if (
        want !== undefined &&
        ai.auto_generated_reminder_template.trigger_threshold_days !== want
      ) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `ActionItem invariant: auto_generated_reminder_template.trigger_threshold_days must be ${want} for cadence '${ai.check_in_cadence}', got ${ai.auto_generated_reminder_template.trigger_threshold_days}.`,
        });
      }
      if (ai.auto_generated_reminder_template.cadence !== ai.check_in_cadence) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `ActionItem invariant: auto_generated_reminder_template.cadence must equal check_in_cadence ('${ai.check_in_cadence}'), got '${ai.auto_generated_reminder_template.cadence}'.`,
        });
      }
    }
  });

const Stage3a1LlmRecommendationSchema = z.object({
  recommendation_id: z.string().regex(/^REC-[A-Z]{3}-\d{3}$/),
  // source_file_path omitted — derived by the harness from the rec_id.
  category: RecommendationCategoryEnum,
  status: z.enum(["Active", "Active-Cautioned", "Advanced", "Landmine", "Deprecated"]),
  position_in_sequence: z.number().int(),
  plan_section: PlanSectionEnum.nullable(),
  subsection_within_section: z.string().nullable(),
  co_triggered_with: z.array(z.string()),
  quantified_impact: QuantifiedImpactSchema,
  scenario_range: ScenarioRangeSchema.nullable(),
  timing_bucket: TimingBucketEnum,
  owner: ActionOwnerEnum,
  // owner_name omitted — always null at Stage 3a.1.
  decisions_needed: z.boolean(),
  cluster_id: z.string().nullable(),
  cluster_sequence_closer: z.string().nullable(),
  action_items: z.array(Stage3a1LlmActionItemSchema),
  landmine: z.boolean(),
  landmine_status: z.string(),
  default_excluded: z.boolean(),
  plan_output_variant: z.enum(["default_excluded", "authorized"]).nullable(),
  match_strength: z.enum(["strong", "borderline"]),
  _audit_notes: z.string().nullable(),
});

export const Stage3a1LlmRawOutputSchema = z.object({
  batch_index: z.number().int().nonnegative(),
  total_batches: z.number().int().positive(),
  recommendations: z.array(Stage3a1LlmRecommendationSchema),
  _stage_flags: SequencerFlags3aSchema,
});

export type Stage3a1LlmRawOutput = z.infer<typeof Stage3a1LlmRawOutputSchema>;
export type Stage3a1LlmRecommendation = z.infer<typeof Stage3a1LlmRecommendationSchema>;
export type Stage3a1LlmActionItem = z.infer<typeof Stage3a1LlmActionItemSchema>;

// ────────────────────────────────────────────────────────────────────────
// JSON Schema for Anthropic tool use.
//
// Phase 3.1c moves Stage 3a.1 from text-output JSON to tool-use schema
// enforcement. The Anthropic SDK validates the model's output against this
// JSON Schema BEFORE the response returns; the model literally cannot emit
// extra keys (additionalProperties: false at every level), wrong enum values,
// or wrong-shape sub-objects. This solves the dominant Step 2 failure modes:
// _stage_flags sub-shape inventions, scenario_range field errors, and
// invalid timing_bucket / partner_type / duration_class enum values.
//
// Zod 4's native `toJSONSchema()` handles structural fields cleanly but
// silently drops `superRefine` constraints. We restore those as JSON Schema
// `allOf` + `if/then` rules so QuantifiedImpact State invariants and
// ActionItem lifecycle invariants are enforced at the protocol layer too.
// The zod superRefine validation in Stage3a1ResponseBodySchema remains as a
// safety net; in practice tool use should make schema-validation retries
// extremely rare.
// ────────────────────────────────────────────────────────────────────────

// State invariants for QuantifiedImpact. Mirror the four `superRefine` rules
// in QuantifiedImpactSchema above. The four states are NOT a clean partition
// (a record can satisfy multiple states' base predicates simultaneously, e.g.
// estimate===null applies to both B and D), so we express each rule as an
// independent if/then constraint inside an `allOf` rather than a discriminator.
const QUANTIFIED_IMPACT_STATE_INVARIANTS = [
  {
    // State A: estimate populated → no blocked_inputs, no alternative_values, no qualitative_phrasing.
    if: { properties: { estimate: { type: "object" } }, required: ["estimate"] },
    then: {
      properties: {
        blocked_inputs: { maxItems: 0 },
        alternative_values: { maxItems: 0 },
        qualitative_phrasing: { type: "null" },
      },
    },
  },
  {
    // State B: blocked_inputs populated → estimate must be null.
    if: { properties: { blocked_inputs: { minItems: 1 } } },
    then: { properties: { estimate: { type: "null" } } },
  },
  {
    // State C: alternative_values populated ⇔ pending_reconciliation === true. Biconditional needs both directions.
    allOf: [
      {
        if: { properties: { alternative_values: { minItems: 1 } } },
        then: { properties: { pending_reconciliation: { const: true } } },
      },
      {
        if: { properties: { pending_reconciliation: { const: true } } },
        then: { properties: { alternative_values: { minItems: 1 } } },
      },
    ],
  },
  {
    // State D: reason_no_formula populated → estimate=null, formula_id=null, qualitative_phrasing must be a string.
    if: {
      properties: { reason_no_formula: { type: "string" } },
      required: ["reason_no_formula"],
    },
    then: {
      properties: {
        estimate: { type: "null" },
        formula_id: { type: "null" },
        qualitative_phrasing: { type: "string" },
      },
    },
  },
];

// ActionItem lifecycle invariants. Mirror the superRefine rules in
// Stage3a1LlmActionItemSchema. Cadence-to-trigger_threshold_days mapping is
// kept zod-only — encoding all five enum→number mappings in JSON Schema is
// possible but verbose; the mapping is deterministic and the model has
// little incentive to fabricate a wrong number when the cadence enum is
// already protocol-pinned.
const ACTION_ITEM_LIFECYCLE_INVARIANTS = [
  {
    // long_running ⇔ check_in_cadence !== null AND auto_generated_reminder_template !== null.
    allOf: [
      {
        if: { properties: { duration_class: { const: "long_running" } } },
        then: {
          properties: {
            check_in_cadence: { type: "string" },
            auto_generated_reminder_template: { type: "object" },
          },
        },
      },
      {
        if: { properties: { duration_class: { not: { const: "long_running" } } } },
        then: {
          properties: {
            check_in_cadence: { type: "null" },
            auto_generated_reminder_template: { type: "null" },
          },
        },
      },
    ],
  },
  {
    // partner_required ⇔ partner_type !== null.
    allOf: [
      {
        if: { properties: { partner_required: { const: true } } },
        then: { properties: { partner_type: { type: "string" } } },
      },
      {
        if: { properties: { partner_required: { const: false } } },
        then: { properties: { partner_type: { type: "null" } } },
      },
    ],
  },
];

type JsonSchemaObject = {
  type?: string;
  properties?: Record<string, JsonSchemaObject>;
  items?: JsonSchemaObject;
  allOf?: unknown[];
  [k: string]: unknown;
};

function buildToolInputSchema(): Record<string, unknown> {
  // Drop the $schema declaration — Anthropic's tool input_schema field
  // doesn't expect it (it's not a top-level JSON Schema document, it's an
  // input shape the model produces).
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { $schema, ...base } = z.toJSONSchema(Stage3a1LlmRawOutputSchema) as Record<
    string,
    unknown
  > & { $schema?: string };
  const root = base as JsonSchemaObject;

  // Inject QuantifiedImpact State invariants.
  const recItems = root.properties?.recommendations?.items;
  const qi = recItems?.properties?.quantified_impact;
  if (qi) {
    qi.allOf = [...(qi.allOf ?? []), ...QUANTIFIED_IMPACT_STATE_INVARIANTS];
  }

  // Inject ActionItem lifecycle invariants.
  const ai = recItems?.properties?.action_items?.items;
  if (ai) {
    ai.allOf = [...(ai.allOf ?? []), ...ACTION_ITEM_LIFECYCLE_INVARIANTS];
  }

  return root as Record<string, unknown>;
}

export const STAGE3A1_TOOL_INPUT_SCHEMA: Record<string, unknown> = buildToolInputSchema();

export const STAGE3A1_TOOL_NAME = "submit_quantified_batch";
export const STAGE3A1_TOOL_DESCRIPTION =
  "Submit the per-batch quantified recommendations. Call this tool exactly once with the full batch result. The schema enforces State A/B/C/D invariants, ActionItem lifecycle invariants, and SequencerFlags3a sub-object shapes — your input must satisfy all of them.";

// ────────────────────────────────────────────────────────────────────────
// Post-fill: deterministic transform from the narrower LLM output to the
// full Stage3a1ResponseBody shape. The harness calls this after parsing
// the LLM response, then re-validates the result against the full schema.
//
// `recIdToFilePath` carries the per-rec source file paths that the harness
// resolved during KB load (Phase 1 step 1.1). Any rec_id missing from the
// map gets an empty source_file_path; downstream tools may flag this, but
// the schema accepts any non-throwing string.
// ────────────────────────────────────────────────────────────────────────

export function harnessPostFillFields(
  raw: Stage3a1LlmRawOutput,
  recIdToFilePath: Map<string, string>,
): Stage3a1ResponseBody {
  return {
    batch_index: raw.batch_index,
    total_batches: raw.total_batches,
    _stage_flags: raw._stage_flags,
    recommendations: raw.recommendations.map((rec) => ({
      ...rec,
      source_file_path: recIdToFilePath.get(rec.recommendation_id) ?? "",
      owner_name: null,
      action_items: rec.action_items.map((ai) => ({
        ...ai,
        owner_name: null,
        parent_action_item_id: null,
        is_derivative_reminder: false,
        source_plan_id: null,
      })),
    })),
  };
}

// ────────────────────────────────────────────────────────────────────────
// Wrappers with metadata: Stage3a1Result (success) / Stage3a1ResultFailed
// ────────────────────────────────────────────────────────────────────────

import type { StageMetadata } from "./clientProfile";

export interface Stage3a1Metadata extends StageMetadata {
  // Inherits: stage_version, model_used, input_token_count, output_token_count,
  // cache_creation_input_tokens, cache_read_input_tokens, attempts_made,
  // attempt_history, duration_ms, source_fr_content_hash, parsed_at.
  // Stage 3a.1 also tracks per-batch context.
  batch_index: number;
  total_batches: number;
}

export interface Stage3a1Result {
  batch_index: number;
  total_batches: number;
  recommendations: SequencedRecommendation[];
  _stage_flags: SequencerFlags3a;
  _metadata: Stage3a1Metadata;
}

export type Stage3a1FailureType =
  | "kb_load_failed"
  | "json_parse_failed"
  | "schema_validation_failed"
  | "api_error"
  | "max_retries_exceeded"
  | "context_overflow"
  | "fr_extraction_failed";

export interface Stage3a1ResultFailed {
  _stage_status: "FAILED";
  _failure_type: Stage3a1FailureType;
  _failure_reason: string;
  _failure_context: {
    batch_index: number;
    missing_rec_id?: string;
    parse_error?: string;
    validation_errors?: string[];
    raw_response?: string;
    parsed_response?: unknown;
    api_error?: string;
    attempts_made: number;
    last_failure_type?: "json_parse_failed" | "schema_validation_failed";
    estimated_input_tokens?: number;
  };
  _metadata: Partial<Stage3a1Metadata>;
}

// Type guard so callers can narrow without inspecting the discriminator.
export function isStage3a1ResultFailed(
  r: Stage3a1Result | Stage3a1ResultFailed,
): r is Stage3a1ResultFailed {
  return (r as Stage3a1ResultFailed)._stage_status === "FAILED";
}

// Re-export for convenience.
export type { ActionItem, SequencedRecommendation, SequencerFlags3a };
